# Generated by Django 5.1.2 on 2024-10-15 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='detail',
        ),
        migrations.CreateModel(
            name='SubPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('pricing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pricing')),
            ],
        ),
    ]
