# Generated by Django 5.1.2 on 2024-10-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_pricing_detail_subpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='highlight_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
