# Generated by Django 5.1.2 on 2024-10-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_subpricing_pricing_subpricing_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpricing',
            name='pricing',
            field=models.ManyToManyField(related_name='subpricing_set', to='main.pricing'),
        ),
    ]
