# Generated by Django 5.1.2 on 2024-10-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_subscriber_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='address',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='subs/'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
