# Generated by Django 5.1.2 on 2024-10-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_subscriber_address_alter_subscriber_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='img',
            field=models.ImageField(null=True, upload_to='subs/'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
